### ISSUE TITLE
Docker build fails on dependency 

### ISSUE THREAD

**Issue by xenithorb** [twostairs/paperwork#845] opened 2017-11-06 17:49 UTC
```
bootstrap#3.3.7 app/js/bower_components/bootstrap
└── jquery#1.11.3

rangy#1.3.0 app/js/bower_components/rangy

bootstrap-css-only#3.3.7 app/js/bower_components/bootstrap-css-only

font-awesome#4.7.0 app/js/bower_components/font-awesome
module.js:471
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R $UID:$GID /app && chmod +x /usr/local/bin/docker-runner.sh' returned a non-zero code: 1
```

Can you consider version locking on known good versions so building isn't such a dependency-roulette?

**Comment by virtadpt** [comment] 2017-11-18 18:17
I ran `npm install jshint` and re-ran `gulp` and it seems to have worked.  Wonder why it's not listed as a dependency...

**Comment by Liongold** [comment] 2017-12-21 14:15
Can someone confirm that this issue is a duplicate of #833? I'll leave this issue open and label it as `duplicate` until someone replies.

**Comment by Liongold** [comment] 2018-03-08 17:03
Since nobody has replied to this issue and #833 has already been closed, this issue will also be closed. Thank you for using Paperwork. If you encounter any issues, feel free to open a new issue.

**Closed by Liongold** 2018-03-08 17:03 UTC
Labels: duplicate
