### ISSUE TITLE
Move JS dependencies into bower

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#113] opened 2015-01-26 15:38 UTC
Bower allows you to manage dependencies of your frontend. I suggest you to move everything you did not write into bower.json and just install the deps before the building the application itself. There's no reason to hold all the third-party stuff here.

**Comment by devilx** [comment] 2015-01-26 17:14
Duplicate of #58, please continue there. :-)

**Closed by devilx** 2015-01-26 17:14 UTC
Labels: duplicate
