### ISSUE TITLE
not able to create a note in the online demo (note books can be created)

### ISSUE THREAD

**Issue by kaystrobach** [twostairs/paperwork#110] opened 2015-01-26 12:30 UTC
```
 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://demo.paperwork.rocks/api/v1/notebooks/887/notes
```

**Comment by devilx** [comment] 2015-01-26 12:37
Could you show us the screenshot of that issue please? We need a further more lines of the error for this to fix. Thanks!

**Comment by kaystrobach** [comment] 2015-01-26 12:39
@devilx currently not possible, as the demo is down ...

![2015-01-26_13-38-58](https://cloud.githubusercontent.com/assets/1185776/5899749/bdc78ce8-a560-11e4-8389-098361812c67.png)

**Comment by kaystrobach** [comment] 2015-01-26 12:40
perhaps this was the main issue and the reason for the error, in the meantime the frontpage was maybe cached ...

**Comment by devilx** [comment] 2015-01-26 12:41
Could you try again please?

**Comment by kaystrobach** [comment] 2015-01-26 12:45
steps to reproduve,

* register
* create notebook
* select the notebook
* try to create new note

ajax response:

```
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (SQL: insert into `versions` (`title`, `content`, `updated_at`, `created_at`) values (, , 2015-01-26 12:42:31, 2015-01-26 12:42:31))","file":"\/srv\/paperwork\/frontend\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
```

![2015-01-26_13-44-35](https://cloud.githubusercontent.com/assets/1185776/5899822/90287972-a561-11e4-9c98-9273eba068cb.png)

![2015-01-26_13-44-20](https://cloud.githubusercontent.com/assets/1185776/5899825/9730ae24-a561-11e4-8747-c5e2cd17a532.png)
![2015-01-26_13-43-44](https://cloud.githubusercontent.com/assets/1185776/5899828/9c89ad44-a561-11e4-81c6-2a06cbb3ba6e.png)

**Comment by kaystrobach** [comment] 2015-01-26 12:46
PS: it's still broken, but imho it's just a migration issue or a missing migration :smile:

**Comment by devilx** [comment] 2015-01-26 12:47
Thank you for this extended info! It appears to be a duplicate of #100. Going to close this now, as we're working on #100 already. Feel free to subscribe there. :+1:

**Closed by devilx** 2015-01-26 12:47 UTC
Labels: bug
