### ISSUE TITLE
Can't add Notice

### ISSUE THREAD

**Issue by N00D13** [twostairs/paperwork#105] opened 2015-01-26 08:25 UTC
Mac OSX 10.10.1
Chromium V 42.0.22

**Comment by hoffi** [comment] 2015-01-26 08:42
Same here.
OS X 10.9.5 on Chrome and Safari. 

This error is returned by the request:
```json
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null (SQL: insert into `versions` (`title`, `content`, `updated_at`, `created_at`) values (, , 2015-01-26 08:41:52, 2015-01-26 08:41:52))","file":"\/srv\/paperwork\/frontend\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":625}}
```

**Comment by devilx** [comment] 2015-01-26 09:40
Duplicate of #100.

**Closed by devilx** 2015-01-26 09:40 UTC
Labels: bug, duplicate
