### ISSUE TITLE
Navigation dissapears when in edit mode

### ISSUE THREAD

**Issue by davidtessier** [twostairs/paperwork#866] opened 2018-02-06 18:25 UTC
Hi,
I installed Paperwork on my LAMP server and have a strange issue (at least I think it's an issue) where I don't see the paperwork note navigation sections when editing a note. 
I have included 2 screenshots in the link below that show you what I see in edit mode, and what I see in the desktop mode. 
 
[Link to screenshots](https://imgur.com/a/vo39I)

I don't have any errors in my `/var/log/apache/error.log`
I see an error in the Firefox console. I have included it below. 

```
Error: $rootScope.templateNoteEdit.version is undefined
thisController/<@https://notes.something.ca/js/paperwork.min.js:628:21
$digest@https://notes.something.ca/js/angular.min.js:12703:23
$apply@https://notes.something.ca/js/angular.min.js:12968:13
done@https://notes.something.ca/js/angular.min.js:8479:34
completeRequest@https://notes.something.ca/js/angular.min.js:8693:7
createHttpBackend/</xhr.onreadystatechange@https://notes.something.ca/js/angular.min.js:8632:11
angular.min.js:10160:18
consoleLog/<
https://notes.something.ca/js/angular.min.js:10160:18
$ExceptionHandlerProvider/this.$get</<
https://notes.something.ca/js/angular.min.js:7427:7
$digest
https://notes.something.ca/js/angular.min.js:12722:19
$apply
https://notes.something.ca/js/angular.min.js:12968:13
done
https://notes.something.ca/js/angular.min.js:8479:34
completeRequest
https://notes.something.ca/js/angular.min.js:8693:7
createHttpBackend/</xhr.onreadystatechange
https://notes.something.ca/js/angular.min.js:8632:11
```

Is there anywhere I may see more diagnostic info to post? Why don't I see the navigation pane in edit mode? 

Thank you.

**Comment by Liongold** [comment] 2018-02-07 18:08
@davidtessier That is intended. In fact, the issue is the empty side space you see on the left. That is a bug. Thank you for reporting it.

**Comment by Liongold** [comment] 2018-03-08 20:08
This should be fixed in the latest pull request merged to the `1` branch. Please pull the latest code and try again. Thank you for your interest in Paperwork. This issue will be closed. If you encounter any new issues, feel free to open a new issue.

**Closed by Liongold** 2018-03-08 20:08 UTC
Labels: bug
