### ISSUE TITLE
Last Name requires only letters and numbers. Should this not be letters and symbols?

### ISSUE THREAD

**Issue by RoryOSiochain** [twostairs/paperwork#133] opened 2015-01-28 14:39 UTC
My Surname has either a space or apostrophe in it. Most double barrel surnames would tend to use a dash. Not sure if anyone uses numbers in their name though.

**Comment by jamesrascal** [comment] 2015-01-28 16:47
This is related to #86

**Comment by devilx** [comment] 2015-01-30 23:50
Exactly! :-) Duplicate of #86 .

**Closed by devilx** 2015-01-30 23:50 UTC
