### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by jasondavis** [twostairs/paperwork#162] opened 2015-01-30 22:22 UTC
As mentioned in another comment, I am very grateful for this application.  It is so perfect for me because of my desire to self-host and own my data + the fact it;s built on my language of choice (PHP+Laravel) it is a dream come true!  Also I use Evernote daily for so many things and this app is the perfect self-hosted replacement that I thought I would never have, so thank you!

Some features that I would like to see....

- When editing or adding a new note, there is no indication that the note is completed saving.  Would like some sort of notice in the UI to allow a user to know the save is still processing.

- Would like the Editor to be expanded upon.  I realize the editor uses a 3rd part library ckeditor but that could be n advantage as well.  Perhaps ckeditor has some add-ons to add more functionality to it.  I would realllllly be happy with some sort of HTML view, so that the HTML can be edited for a note as well in addition to the standard WYSIWYG.

- Would be nice to be able to Drag and Drop images into an area of the page to have it automatically start uploading a file.Right now to add an image or file you click the button and browse to your file and then click to upload it.  Most modern apps allow drag and drop to upload as well and it would be nice here!

- When editing or adding a note I would like keyboard shortcut so I can simply hit CTRL+S to save the Note.

- Expanding on the Keyboard shortcuts, CTRL+N would open the page to add a new Note!

- When viewing a Note, there is no way to edit it unless I go up to the menu and find the edit note link/button.  Perhaps add some small Edit Note button when viewing a Note up in the top Meta area.  There are already button on the top right of a note, it could be added to those buttons.

- Another idea for a quick method to Edit a note would be in the Note List of a Notebook.  When you Right Click a Note there could be a custom Context menu with an Edit note button there...this is how Evernote has it!  

- Password Protected Notes!  Add ability to password protect some Notes on a per-note basis!  I often use my Evernote and eventually PaperWork for storing account and server login type data.  It would be nice to make these notes password protected from prowling eyes/users that could get on my computer or access the App if it was on the web.

Thats all for now, I would really love to hear a response and feedback on any of this?  Loving where this app is going keep up the work, thanks!

- 
UPDATE

Sorry after reading through pages and pages of issues I see most of my request have already been mentioned!  There might be something new here though

**Comment by joshlemer** [comment] 2015-01-30 23:06
@jasondavis Thank you for this issue! These are great ideas. Some thoughts:

* Could you go into more detail or provide an example of an application that uses this drag and drop functionality? It's not clear to me how this would work.

* I love the password protected idea! Maybe this could also apply to entire notebooks.

**Comment by joshlemer** [comment] 2015-01-30 23:24
Maybe we could use something like [CryptoJS](https://code.google.com/p/crypto-js/) to encrypt notes client-side with a password.

**Comment by joshlemer** [comment] 2015-01-31 00:29
Also note that double clicking a note takes you to its edit page. But if @devilx thinks it's appropriate, I have a branch up where there's an edit button added at the top right as well. If he thinks that's a good idea I'll make a Pull Request. Here's what it looks like
![screenshot from 2015-01-30 18 22 23](https://cloud.githubusercontent.com/assets/5122903/5985822/d7a0fa0a-a8ad-11e4-8625-55b8597dd678.png)

**Comment by devilx** [comment] 2015-01-31 08:42
Hey there @jasondavis,

thank you for your valuable feedback. Happy to see that you like the project! Let me answer a few of your ideas quickly:

1. Duplicate of #102 

2. HTML support isn't planned yet (as it would be hard for us to validate and fix it, in order to avoid the user breaking the whole web-ui by writing malformed HTML code), but there is an issue for extending Paperwork in order to allow Markdown, for example: #95.

3. This actually is already possible. Please create a new note, go into edit mode and drag *anything* into your browser's window. You should see a blue highlighting. If this doesn't work for you, please report a new issue containing info about your operating system and browser (+version). Thanks!

4. Duplicate of #104.

5. Same as 4.

6. You could double-click the note within the notes-list in order to launch the editor. This would be option two.

7. Yupp, this will be option number three, that should be done in #24.

8. Could you please copy & paste this into a new issue here on GitHub, so that people could comment separately on that?

@joshlemer what was planned so far, was using SJCL (#22) in order to encrypt all the content on the client side. That's not in order to provide password authentication for separate notes or notebooks, though, but rather for making even the transferred data more secure & private.

@jasondavis thanks for this issue! I'm going to close it now. If you should have more suggestions, please create separate issues for each of them, so we can more easily discuss and eventually plan implementation. :+1:

**Closed by devilx** 2015-01-31 08:42 UTC
Labels: design required, enhancement, help wanted
