### ISSUE TITLE
New Note not available on Safari

### ISSUE THREAD

**Issue by RoryOSiochain** [twostairs/paperwork#134] opened 2015-01-28 14:46 UTC
Able to create collection, but not a new note using safari for mac. Can edit notes created in Chrome

**Comment by iamgeef** [comment] 2015-01-29 06:11
I've just tested in Safari (v8.0.3) on Yosemite and it works fine for me. Are any errors listed in Safari's error console?

**Comment by RoryOSiochain** [comment] 2015-01-29 11:16
No errors are output. The issue seems to be with the menu. There is space for the option but it doesn't appear.

I'm running Safari Version 8.0.3 (10600.3.18)

![screenshot 2015-01-29 11 09 26](https://cloud.githubusercontent.com/assets/721089/5956663/0e2bfe64-a7a8-11e4-88d3-2630c3d088cb.png)
![screenshot 2015-01-29 11 09 59](https://cloud.githubusercontent.com/assets/721089/5956664/0e5cf5c8-a7a8-11e4-9339-57d1167e2d44.png)

**Comment by iamgeef** [comment] 2015-01-29 11:39
Ahh, I see. I think that's by design. Possibly due to the way the database references the notes (@devilx could confirm), you have to create a notebook first to save the note in.
Same result on Chrome:
![screen shot 2015-01-29 at 10 25 31 pm](https://cloud.githubusercontent.com/assets/10751405/5956809/d7b40cba-a805-11e4-8b2c-aea6de87e2b6.png)

Create a notebook first, and then you'll be able to create the note.

**Comment by RoryOSiochain** [comment] 2015-01-29 11:47
Yep, my bad! Closing issue.

**Comment by devilx** [comment] 2015-01-31 00:12
@iamgeef was right here, it's by design. Now, my question here would be: Is it "broken by design"? Is this UI behaviour understandable for everyone, or will it lead to confusion? Surely something to think about.

**Comment by ponychicken** [comment] 2015-02-03 12:23
I think it's broken, I just stumbled on the same.

Suggested UI: new note is never gray, and when clicked while no notebook is active or existing, a selection/creation thing pops up

**Comment by devilx** [comment] 2015-02-08 11:03
How about we leave it gray, as it is right now, but build in popups that describe why it is gray? The "graying out" of menues usually is a standard across all desktops, therefor I would like to keep it like this, but also provide users an information about why it's impossible to create a new note when there is not notebook available. "All notes" is not a notebook, but as of today, notes expect to be placed inside a notebook.

**Comment by Liongold** [comment] 2015-02-10 19:32
Maybe have a slight gray for the text as well? So that the text is visible and maybe as a tooltip have something like: "This is disabled because....".

**Comment by devilx** [comment] 2015-02-10 21:26
Which text do you refer to? The menu text currently already is slightly grayed out.

**Comment by Liongold** [comment] 2015-02-11 20:15
In the screenshot above and in my install, the New Note text is not gray but invisible.

**Comment by devilx** [comment] 2015-02-15 10:58
Apparently, the color used for graying out is invisible to some display color configurations. This needs to be fixed within the paperwork-variables.less.

**Comment by Liongold** [comment] 2015-03-29 18:10
This has been fixed in #290. If you encounter this issue again, please open a new issue.

**Closed by Liongold** 2015-03-29 18:10 UTC
Labels: bug
