### ISSUE TITLE
Proper backup/restore method?

### ISSUE THREAD

**Issue by DeviantEng** [twostairs/paperwork#127] opened 2015-01-27 16:40 UTC
Has there been any thought into backups and restore?  I assume notes are stored in the database, so I could see this falling back to normal mariadb/mysql backups, yes?

Any chance of a file-based backup?  It would fit better with my environment, but can do db backups if that's recommended.

Thanks!

**Comment by devilx** [comment] 2015-01-27 16:43
Duplicate of #12 and #13. :-) Please continue there.

**Closed by devilx** 2015-01-27 16:43 UTC
Labels: duplicate
