### ISSUE TITLE
Code Snippet - Formatting is missing

### ISSUE THREAD

**Issue by jgreth** [twostairs/paperwork#448] opened 2015-07-08 09:50 UTC
When you make a note with a code snippet in it, this code shows formatted (syntaxhighlighting / colors) in the editor, but when you view it in library / normal (web-)view there is no color highlighting in it.

Editor:
![editor](https://cloud.githubusercontent.com/assets/2305066/8567698/cebc54f2-2567-11e5-9bfb-a9bd7586cda0.jpg)

Normal:
![normal](https://cloud.githubusercontent.com/assets/2305066/8567699/cedc7ce6-2567-11e5-8ad9-0be4d64f3590.jpg)

**Comment by Baldrs** [comment] 2015-07-08 10:11
That's a duplicate of #109. We know about this and someday we'll fix that.

**Closed by Baldrs** 2015-07-08 10:11 UTC

**Comment by Baldrs** [comment] 2015-07-08 11:31
PS Is that PHP4 code?

**Comment by jgreth** [comment] 2015-07-08 12:30
Oh, sorry. Didn't see #109 
The Code was just as example which was one of the first results when i googled "PHP example Code"... :smile:  So it was just "foo bar"... :smile:
