### ISSUE TITLE
tags are not removed automatically

### ISSUE THREAD

**Issue by THS-on** [twostairs/paperwork#205] opened 2015-02-04 19:47 UTC
When i create a new tag in a note, the tag will be added in the tag list. But when i remove the tag from all the notes that use the tag, the tag is still there. 
Is there a way to delete the tag over the interface?
If not, can that be added, becaue its annoying to delete the tags in the database.
Thanks THS-on

**Comment by devilx** [comment] 2015-02-06 21:36
Duplicate of #177. Please also check out this comment: https://github.com/twostairs/paperwork/issues/177#issuecomment-72559453

**Closed by devilx** 2015-02-06 21:36 UTC
Labels: duplicate
