### ISSUE TITLE
Installing Paperwork on Ubuntu 14.10 issue

### ISSUE THREAD

**Issue by narmadashanmugam** [twostairs/paperwork#434] opened 2015-06-26 08:59 UTC
On installing Paperwork on Ubuntu 14.10 was carried out as shown in the link https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10
There was no error.
But on accessing the localhost i get the following error shown in attachment.
I am not able to identify it.
![30](https://cloud.githubusercontent.com/assets/13046322/8374044/a1052194-1c0f-11e5-9b6e-46f6b4df31ec.png)

**Comment by Baldrs** [comment] 2015-06-26 09:46
Try lateste develop branch

**Comment by Baldrs** [comment] 2015-06-26 09:46
Duplicate of #420

**Closed by Baldrs** 2015-06-26 09:46 UTC

**Comment by narmadashanmugam** [comment] 2015-06-26 10:19
on replacing the latest branch source should I issue any commands for build or restart. Because I am not getting any response from http://localhost/login

**Comment by Baldrs** [comment] 2015-06-26 10:27
You need to rebuild everything again when you switch branches.

**Comment by narmadashanmugam** [comment] 2015-06-26 10:29
Rebuild commands please

**Comment by Baldrs** [comment] 2015-06-26 10:32
RTFM https://github.com/twostairs/paperwork/wiki/Initial-installation
