### ISSUE TITLE
Tags tab ui error?

### ISSUE THREAD

**Issue by OmgImAlexis** [twostairs/paperwork#101] opened 2015-01-26 04:40 UTC
Currently if you enter a tag and then press tab or click anywhere other than the tag input you're left with the tag in "tag" form and the text.

![gui error](https://cloud.githubusercontent.com/assets/6525926/5895392/512f0a40-a56d-11e4-9ce9-66931523391f.PNG)

**Comment by devilx** [comment] 2015-01-26 09:45
That's another issue that would go into @timschlechter's https://github.com/timschlechter/bootstrap-tagsinput repo first and then being pulled into Paperwork. Just like #96.

**Comment by OmgImAlexis** [comment] 2015-01-26 09:50
#101 doesn't seem to be an issue with @timschlechter's https://github.com/timschlechter/bootstrap-tagsinput as the demo pages for it don't seem to have this issue at all.

I just went to check if the paperwork demo and the tagsinput demo are running the same version and it seems paperwork's demo is down?
![server down](https://cloud.githubusercontent.com/assets/6525926/5897846/ae984cac-a598-11e4-857e-876cb8e62ae9.PNG)

**Comment by devilx** [comment] 2015-01-26 10:06
@OmgImAlexis Whoopsie. Yeah, it should be back up again. That's a $5 digitalocean droplet with not enough RAM to serve the current load.

**Comment by swengmatt** [comment] 2015-01-31 04:09
I am unable to reproduce this.

**Comment by devilx** [comment] 2015-01-31 08:48
Then let's close this issue. @OmgImAlexis if you're still having trouble, while using the latest GIT version please re-open.

**Closed by devilx** 2015-01-31 08:48 UTC
Labels: bug, help wanted

**Comment by OmgImAlexis** [comment] 2015-01-31 09:22
@devilx This was on the demo site and I can't currently test if that's still an issue as the demo is currently broken and I don't have a spare machine to test this myself.
