### ISSUE TITLE
Paperwork installation in ubuntu

### ISSUE THREAD

**Issue by sasisweert** [twostairs/paperwork#433] opened 2015-06-26 06:58 UTC
install npm:
==========

curl:(56) recv failure:connection reset by peer
unexpected end of file..

please give the solution how to resolve it? 

because we are in very critical situation please give the solution...

**Comment by Baldrs** [comment] 2015-06-26 09:47
Duplicate of #432

**Closed by Baldrs** 2015-06-26 09:47 UTC
