### ISSUE TITLE
Last name can't contain spaces

### ISSUE THREAD

**Issue by kiall** [twostairs/paperwork#94] opened 2015-01-25 20:10 UTC
Many last names include spaces, hyphens etc. These characters should be allowed.

The best solution is likely to not restrict the name fields at all, many people have names that don't fit the [A-Za-z]+ regex...

**Comment by JoshTGreenwood** [comment] 2015-01-25 20:13
Duplicate of #86 I believe

**Comment by devilx** [comment] 2015-01-25 20:24
@kiall thanks for reporting, please continue in #86!
@JoshTGreenwood :+1:

**Closed by devilx** 2015-01-25 20:24 UTC
Labels: duplicate
