### ISSUE TITLE
No Login Window

### ISSUE THREAD

**Issue by ccuellar14** [twostairs/paperwork#609] opened 2016-04-11 22:08 UTC
Hi,

I have a problem on final config at PaperWork, in final step in confirmation create account, for a post login, no loading next window.

Attached File demo
![image](https://cloud.githubusercontent.com/assets/16178871/14443778/ed372874-0006-11e6-9f47-0f4a900c18ae.png)

**Comment by Liongold** [comment] 2016-04-26 15:43
@ccuellar14 Can you update Paperwork (develop branch) and try again please?

**Comment by wongalvis** [comment] 2016-06-06 15:22
I think this specific issue only occurs in that old version, after updating it should be fine.

**Comment by Liongold** [comment] 2016-06-09 17:43
Since there hasn't been a reply on this issue and another user has confirmed this issue is fixed, I'll close this issue. If anyone encounters this issue again, please reopen this issue.

**Closed by Liongold** 2016-06-09 17:43 UTC
Labels: pending feedback
