### ISSUE TITLE
import/ export self consistency

### ISSUE THREAD

**Issue by jhellerstedt** [twostairs/paperwork#824] opened 2017-08-02 13:21 UTC
Hi,

I installed this 'as-is', am specifically interested in the import/ export features.

It seems the current export enex file can't be re-imported with the import feature?

However, when I just replaced the EvernoteImport.php file from [JamborJan's fork](https://github.com/JamborJan/paperwork/blob/master/changedfiles/frontend/app/lib/Paperwork/Import/EvernoteImport.php) it seems to fix this self-consistency problem.

Regards,

Jack

**Comment by Liongold** [comment] 2017-08-03 12:08
@jhellerstedt Good to know. 

@JamborJan Can you put your fork's EvernoteImport.php file in a pull request to merge it with the actual Paperwork? Of course, assuming there's nothing Sandstorm-specific.

**Comment by JamborJan** [comment] 2017-08-04 06:19
Hey guys,

I'm doing 3 things differently. I try to explain as best as I can remember, it is some time since I have done this:
1. when importing a new notebook I create a new name with timestamp because otherwise it would crash when multiple imports are done. See [these lines](https://github.com/JamborJan/paperwork/blob/master/changedfiles/frontend/app/lib/Paperwork/Import/EvernoteImport.php#L22).
2. I have created a value "paperwork" because when exporting data this is set as application and the import used to import only files with Evernote set as application. See [these lines](https://github.com/JamborJan/paperwork/blob/master/changedfiles/frontend/app/lib/Paperwork/Import/EvernoteImport.php#L48-L50)
3. I played around with the encoding which is from my point of view not so stable and maybe a bit risky. ee [these lines](https://github.com/JamborJan/paperwork/blob/master/changedfiles/frontend/app/lib/Paperwork/Import/EvernoteImport.php#L60-L79)

From what @jhellerstedt wrote I guess point 2 is worth a try. So I will only send a PR with this change and you can test if this helps.

**Comment by Liongold** [comment] 2017-08-04 15:58
@JamborJan I think point 1 would help as well. I think there were reports of problems with duplicate notebooks and problems with them.

**Comment by Liongold** [comment] 2017-08-04 16:01
And point 3 seems to be a small change as well. Do you mind if you put all the changes in the pull request, again assuming no special relationship with Sandstorm and that they do not introduce regressions please?

**Comment by JamborJan** [comment] 2017-08-04 16:34
Okay @Liongold I added point 1 also to the [PR](https://github.com/twostairs/paperwork/pull/825/commits/7169625f0cdfc8b0c1cba25ad1418a3500e127f9). But point 3 is not so easy. It's still not working very well. There are a lot of different error messages. I improved the error message (see image below) but I was not able to fight them all. When I chose random notes from Evernote and export them I have sometimes success importing them and sometimes not. So I'm not comfortable adding this code to your repository. It would be still unstable. 

Example for failed import:
![bildschirmfoto 2017-08-04 um 18 30 02](https://user-images.githubusercontent.com/7508960/28977657-3e18073e-7943-11e7-9146-6ff2057c38d1.png)

Example for successful import:
![bildschirmfoto 2017-08-04 um 18 31 04](https://user-images.githubusercontent.com/7508960/28977658-3e299e40-7943-11e7-8678-e952ddd3621d.png)

**Comment by Liongold** [comment] 2017-08-07 12:39
@JamborJan Thank you. 

@jhellerstedt Can you, by any chance, test the pull request code and make sure your issue is fixed with that, please?

**Comment by jhellerstedt** [comment] 2017-08-07 12:54
I just switched to issue-824-fix branch on my installation, can confirm that the file exported can now be re-imported without throwing errors.

Thanks @JamborJan

**Comment by Liongold** [comment] 2017-08-17 12:52
@jhellerstedt Good to know. Thank you for testing this.

**Comment by Liongold** [comment] 2017-08-17 12:57
@JamborJan Would #816 help improve the point 3 code? Maybe you could merge your work and that in the pull request and achieve a better result.

**Comment by JamborJan** [comment] 2017-08-20 15:41
Thanks for pointing me at this @Liongold , I'll put it on my backlog for the next tests and build for Sandstorm.

**Comment by Liongold** [comment] 2017-12-21 14:33
@JamborJan Can I close this issue now that the pull requests has been merged?

**Comment by JamborJan** [comment] 2017-12-21 17:31
I'm a bit out of sync with the project. I have no need for this issue to be longer open but I also didn't test or do anything lately. I'll close this issue now but if anybody feels like something went missing please feel free to open a new issue. Thanks.

**Closed by JamborJan** 2017-12-21 17:31 UTC
Labels: pending feedback
