### ISSUE TITLE
Note list error

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#304] opened 2015-03-22 13:58 UTC
The issue is actually appearing whenever a tag is selected.
![2015-03-22 21_57_45-paperwork](https://cloud.githubusercontent.com/assets/6073063/6769595/850e3484-d0de-11e4-9157-3c056743ccfb.png)
Mentioned in https://github.com/twostairs/paperwork/issues/301

**Comment by narcolepticsnowman** [comment] 2015-03-22 20:46
@wongalvis did you run gulp after you pulled last?

**Comment by Baldrs** [comment] 2015-03-22 20:54
@wongalvis consider fresh install before posting a ton of issues

**Comment by narcolepticsnowman** [comment] 2015-03-22 20:55
I can confirm that filtering by tags is completely broken on develop. This was probably related to code changes from #66 . On my system, the list of notes never even shows up. Also the tagid put in to the search box is acting very strange. For some tags I get a reasonable id value, some have the id NaN, and some give me super high numbers for some reason (588359 for example). So I think the whole ui for tags is broken. I will investigate further.

**Comment by Baldrs** [comment] 2015-03-22 20:57
@narcolepticsnowman @devilx stated that #66 broke up a lot of things, and fixing them is appreciated

**Comment by wongalvis** [comment] 2015-03-23 09:57
@Baldrs I checked that it has nothing to deal with gulp/composer or any procedures to be done after git pull updates, nor issues related to previous installations.

**Comment by Baldrs** [comment] 2015-03-28 15:03
Fixed in #320

**Comment by Baldrs** [comment] 2015-03-30 14:46
Merged fixes in develop, @wongalvis @narcolepticsnowman please test latest HEAD of develop

**Comment by wongalvis** [comment] 2015-03-31 03:08
From what I get so far the list didn't display any notes with the tag at all.

**Comment by Baldrs** [comment] 2015-03-31 06:49
Have you pulled the latest develop and rebuilt assets with gulp? Also, have you wiped your cache out?

**Comment by wongalvis** [comment] 2015-03-31 07:10
I've ran php artisan migrate, composer dump-autoload and gulp.

**Comment by Baldrs** [comment] 2015-03-31 19:31
Can you try installing paperwork into another folder with clean database and check again(also please wipe out browser cache, it is javascript related problem)? I had to run `php artisan migrate:refresh` after #66 to get it work, not just `php artisan migrate`

Also if you don't see UUIDs in browser url, you have some obsolete version

**Comment by wongalvis** [comment] 2015-04-01 01:20
What are UUIDs?

**Comment by Baldrs** [comment] 2015-04-01 04:27
Stuff like this 6d90e8c1-9ef5-47d0-820b-9026090fa149

**Comment by wongalvis** [comment] 2015-04-01 05:12
Any idea why?
username: ~/Web/paperwork/frontend $ php artisan migrate:refresh         
**************************************
*     Application In Production!     *
**************************************
 
Do you really wish to run this command? y
**************************************
*     Application In Production!     *
**************************************
 
Do you really wish to run this command? y
Nothing to rollback.
**************************************
*     Application In Production!     *
**************************************
 
Do you really wish to run this command? y
 
 
                                                                                                                                                                                                     
  [Illuminate\Database\QueryException]                                                                                                                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` char(36) not null, `username` varchar(255) not null, `password` varchar(25  
  5) not null, `firstname` varchar(255) not null, `lastname` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0  
   not null, `deleted_at` timestamp null) default character set utf8 collate utf8_general_ci engine = InnoDB)                                                                                        
                                                                                                                                                                                                     
 
 
 
 
                                                                                         
  [PDOException]                                                                         
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists  
                                                                                         
 
 
migrate:refresh [--database[="..."]] [--force] [--seed] [--seeder[="..."]]

**Comment by wongalvis** [comment] 2015-04-01 05:18
And this
PHP Fatal error:  Class 'PaperworkUpdate' not found in /home/pwmvx128/Web/paperwork/frontend/app/start/artisan.php on line 14
Error in exception handler: The stream or file "/home/pwmvx128/Web/paperwork/frontend/app/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /home/pwmvx128/We
b/paperwork/frontend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

**Comment by Baldrs** [comment] 2015-04-01 06:11
Nevermind the last one, just pull again.

**Comment by Baldrs** [comment] 2015-04-01 06:12
I'm afraid you have to start your database from scratch as @devilx mentioned after he merged #66

**Comment by wongalvis** [comment] 2015-04-01 06:58
I'm using VM on Koding, is there any quick way to restore the database?

**Comment by Baldrs** [comment] 2015-04-01 09:03
Use the ~~force~~ terminal ~~Luke~~ @wongalvis and re-create database using mysql command-line tool. ~~The force~~ google is your friend on how to do this because it is very basic task.

**Comment by Baldrs** [comment] 2015-04-01 09:05
Okay I consider that fixed because problems related to updating Koding VM are not related to note list problems. For I cannot reproduce it anymore.

**Closed by Baldrs** 2015-04-01 09:05 UTC
Labels: bug, help wanted

**Comment by wongalvis** [comment] 2015-04-01 09:21
Sorry @Baldrs I am extremely unfamiliar with backend tasks, should I follow the guide in README starting from DROP DATABASE IF EXISTS paperwork; CREATE DATABASE IF NOT EXISTS paperwork DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

**Comment by Baldrs** [comment] 2015-04-01 09:46
@wongalvis these commands will be enough. Then you may `php artisan migrate` to get a new database. BTW you may better use gitter to ask questions.
