### ISSUE TITLE
Update and Migrate to Laravel 5

### ISSUE THREAD

**Issue by jasondavis** [twostairs/paperwork#208] opened 2015-02-05 07:01 UTC
Laravel 5 has been released which has a different folder structure from Laravel 4 and I think it would be a good idea to update Paperwork to use Laravel 5 just for the sake of staying up to date with the latest.  What are the thoughts on this?

**Comment by Baldrs** [comment] 2015-02-05 08:49
Wow, good news, lets all read [this][1]


[1]: http://laravel.com/docs/5.0/upgrade#upgrade-5.0

**Comment by Liongold** [comment] 2015-02-05 09:07
Duplicate of #54

On Thursday, February 5, 2015, Arseniy Lozicki <notifications@github.com>
wrote:

> Wow, good news, lets all read this
> <http://laravel.com/docs/5.0/upgrade#upgrade-5.0>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twostairs/paperwork/issues/208#issuecomment-73012910>.
>


-- 
Sincerely,
Jean Spiteri.

**Closed** 2015-02-05 09:08 UTC
