### ISSUE TITLE
Feature Request: Replace note view with editor.

### ISSUE THREAD

**Issue by jsEveryDay** [twostairs/paperwork#716] opened 2016-11-17 17:38 UTC
Would it be possible to have this run just like Evernote?
Where everything loads into the editor instantly, instead of having 2 different views?

I made my own build of CkEditor but still not satisfied.
In a perfect world I would like to run Kendo Editor
Im just not sure how ckeditor posts the changes to the API, so Kendo can replace Ck.

FYI http://demos.telerik.com/kendo-ui/editor/all-tools

**Comment by Liongold** [comment] 2016-11-21 09:18
Isn't this a duplicate of #259? If yes, please close this issue and post your feedback in that please. Thanks for your feedback.

**Closed** 2016-11-21 21:05 UTC
