### ISSUE TITLE
Configuration has not been set correctly. Please try again.

### ISSUE THREAD

**Issue by bu2zhouzhu** [twostairs/paperwork#689] opened 2016-10-06 04:01 UTC
I'm in setup.php setp 1. When I click Next button, the web page shown a red error said 'Configuration has not been set correctly. Please try again.'. Chrome console shown an error said 'Failed to load resource: the server responded with a status of 404 (Not Found)' and 'jquery.js:9664 GET http://192.168.1.3/setup/setup.php 404 (Not Found)'. 

```
send    @   jquery.js:9664
ajax    @   jquery.js:9215
(anonymous function)    @   setup.php:412
dispatch    @   jquery.js:4670
r.handle    @   jquery.js:4338
```

The Next button function:

```
$("#next_btn, #next_btn_mobile").click(function() {
    if(currentStep == 4) {
        data = "";
        var checkboxes = $("#config_form input[type='checkbox']");
        for(var i = 0; i < checkboxes.length; i++) { 
            data += checkboxes[i].name + "=";
            if(checkboxes[i].checked) { 
                data += "true&"
            }else{
                data += "false&"
            }
        }
        $.ajax({
            type: "POST",
            url: "setup/setConfig",
            data: data
        }).success(function() {
            nextStep((currentStep + 1));
        }).error(function() {
            $("#config_not_set").show();
        });
    }else if(currentStep < 7) {
        nextStep((currentStep + 1));
    }
});
```

I debuged it, found that though I'm in setp 1, currentStep was 4. It executed ajax post, and ended in error, so finally $("#config_not_set").show(); executed.

**Comment by bu2zhouzhu** [comment] 2016-10-06 04:14
![](http://imgur.com/a/rv46E)

**Comment by bu2zhouzhu** [comment] 2016-10-06 04:53
Variable currentStep is wrong. Setup page begins with step 4. Though bottom of the page says step 1, it is 4. You can click previous button to bring yourself to step 3 and you need do that. Click Previous button to real step 1 page, and click next button one by one, you can finish setup correctly.

**Comment by Liongold** [comment] 2016-10-07 14:45
What branch are you using? I think this should have been fixed in develop.

**Comment by bu2zhouzhu** [comment] 2016-10-08 02:18
@Liongold I followed [Installing Paperwork on Debian 7](https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Debian-7). 
I download Paperwork using git:
```
git clone https://github.com/twostairs/paperwork.git
```

**Comment by kuc** [comment] 2016-10-08 12:58
Duplicate of #685

**Comment by Liongold** [comment] 2016-10-10 07:12
Can you try using the develop branch?

**Comment by bu2zhouzhu** [comment] 2016-10-10 07:34
@Liongold I have installed paperwork on my raspberry pi. Maybe next time.

**Comment by persianphilosopher** [comment] 2016-12-19 02:01
@Liongold Having been stuck at the same stage for a while, I erased everything and cloned the dev branch. Did composer, npm, bower install and then ran gulp. No errors. 

Going to url/setup also took me to the fourth step. But I clicked previous and made sure that all settings were said to be correct. At step 3, I get "These credentials are correct. Install your Paperwork database by clicking 'Next' below."

Once at step 4, it's again the same red error "Configuration has not been set correctly. Please try again."

The console says:

Failed to load resource: the server responded with a status of 404 (Not Found)
http://url/public/setup/setConfig Failed to load resource: the server responded with a status of 404 (Not Found)
http://url/public/setup/installDatabase Failed to load resource: the server responded with a status of 404 (Not Found)

The setup folder obviously doesn't have those so I don't know what else to do.

**Comment by Liongold** [comment] 2016-12-19 09:21
Can you delete the frontend/app/storage/config/setup file and then rerun the Setup Wizard please?

**Comment by persianphilosopher** [comment] 2016-12-19 17:52
@Liongold exact same problem after deleting "setup". Did it twice, with a clean new attempt as well. 

Are there any logs that I can provide?

**Comment by Liongold** [comment] 2016-12-22 18:00
Do you have a database fully set up?

**Comment by Liongold** [comment] 2016-12-22 18:03
Also do you get a paperwork.json file in `frontend/app/storage/config` after clicking the Next button from Step 4. One last thing to take care of, does the server have enough permissions to write files?

**Comment by persianphilosopher** [comment] 2016-12-22 20:46
yes database is fully setup and permissions are all correct, especially for the ./storage folder. but there is no paperwork.json generated at step 4

**Comment by Liongold** [comment] 2016-12-29 10:33
Do you have any errors in the error log file?

**Comment by persianphilosopher** [comment] 2017-01-08 22:06
in the storage folder logs? no it's empty

**Comment by Liongold** [comment] 2017-01-09 17:38
No in the apache/nginx one. Also, can you list the tables currently available in the database please?

**Comment by persianphilosopher** [comment] 2017-01-20 19:58
i gave up after days of trying. as a last attempt, i reformatted the server to ubuntu and it worked. can't figure out why

**Comment by Liongold** [comment] 2017-01-23 16:51
Can this be closed then?

**Comment by nanu-c** [comment] 2017-01-26 23:47
I have the same error

```
MariaDB [notizen2]> show tables ;
+--------------------+
| Tables_in_notizen2 |
+--------------------+
| attachment_version |
| attachments        |
| language_user      |
| languages          |
| migrations         |
| note_user          |
| notebook_user      |
| notebooks          |
| notes              |
| password_reminders |
| sessions           |
| settings           |
| shortcuts          |
| tag_note           |
| tags               |
| users              |
| versions           |
+--------------------+
17 rows in set (0.00 sec)
```


```
POST /frontend/public/setup/setConfig HTTP/1.1
Host: localhost:83
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: http://localhost:83/frontend/public/setup.php
Content-Length: 91
Cookie: wp-settings-time-1=1484217903; wp-settings-1=libraryContent%3Dbrowse%26editor%3Dhtml%26hidetb%3D1%26advImgDetails%3Dshow%26imgsize%3Dlarge%26editor_plain_text_paste_warning%3D2%26urlbutton%3Dcustom%26editor_expand%3Don%26align%3Dleft
Connection: keep-alive


HTTP/1.1 404 Not Found
Date: Thu, 26 Jan 2017 23:34:22 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Length: 303
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

nothing in the apache log

```
root@01eb0bbec8a6:/app/frontend/app# ls -lah
total 84K
drwxrwxr-x 17 www-data www-data 4.0K Jan 26 23:10 .
drwxrwxr-x  9 www-data www-data 4.0K Jan 26 23:15 ..
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 commands
drwxrwxr-x  5 www-data www-data 4.0K Jan 26 23:10 config
drwxrwxr-x  4 www-data www-data 4.0K Jan 26 22:52 controllers
drwxrwxr-x  4 www-data www-data 4.0K Jan 26 22:52 database
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 extensions
-rw-r--r--  1 www-data www-data 3.4K Jan 26 23:10 filters.php
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 help
drwxrwxr-x  4 www-data www-data 4.0K Jan 26 23:18 js
drwxrwxr-x 25 www-data www-data 4.0K Jan 26 22:52 lang
drwxrwxr-x  5 www-data www-data 4.0K Jan 26 22:52 less
drwxrwxr-x  3 www-data www-data 4.0K Jan 26 22:52 lib
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 models
-rw-r--r--  1 www-data www-data 5.8K Jan 26 23:10 routes.php
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 start
drwxrwxr-x  9 www-data www-data 4.0K Jan 26 22:52 storage
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 tests
-rw-rw-r--  1 www-data www-data  959 Jan 26 22:52 validators.php
drwxrwxr-x  9 www-data www-data 4.0K Jan 26 22:52 views


root@01eb0bbec8a6:/app/frontend/app/config# ls -lah
total 96K
drwxrwxr-x  5 www-data www-data 4.0K Jan 26 23:10 .
drwxrwxr-x 17 www-data www-data 4.0K Jan 26 23:10 ..
-rw-rw-r--  1 www-data www-data 8.4K Jan 26 22:52 app.php
-rw-rw-r--  1 www-data www-data 2.1K Jan 26 22:52 auth.php
-rw-rw-r--  1 www-data www-data 2.7K Jan 26 22:52 cache.php
-rw-rw-r--  1 www-data www-data  444 Jan 26 22:52 compile.php
-rw-r--r--  1 www-data www-data 4.1K Jan 26 23:10 database.php
-rw-rw-r--  1 www-data www-data  283 Jan 26 22:52 ldap.php
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 local
-rw-rw-r--  1 www-data www-data 3.9K Jan 26 22:52 mail.php
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 packages
-rw-r--r--  1 www-data www-data 6.3K Jan 26 23:10 paperwork.php
-rw-rw-r--  1 www-data www-data 2.1K Jan 26 22:52 queue.php
-rw-rw-r--  1 www-data www-data 1.6K Jan 26 22:52 remote.php
-rw-rw-r--  1 www-data www-data  669 Jan 26 22:52 services.php
-rw-rw-r--  1 www-data www-data 4.5K Jan 26 22:52 session.php
drwxrwxr-x  2 www-data www-data 4.0K Jan 26 22:52 testing
-rw-rw-r--  1 www-data www-data  907 Jan 26 22:52 view.php
-rw-rw-r--  1 www-data www-data  883 Jan 26 22:52 workbench.php

root@01eb0bbec8a6:/app/frontend/app/config# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

```

**Comment by nanu-c** [comment] 2017-01-26 23:48
And the solution is enable mod_rewrite in apache and allow custom .htacces files ... so it's not paperwork but configuration of webserver

**Comment by persianphilosopher** [comment] 2017-01-27 07:02
By custom access you mean chmod the .htaccess?

**Comment by nanu-c** [comment] 2017-01-28 15:18
Yes thats it.

**Comment by JustinHendryx** [comment] 2017-02-06 02:48
Had this issue as well on a new install of Apache and forgot to explicitly enable mod_rewrite. After switching it on, everything is working great.

**Comment by Liongold** [comment] 2017-02-07 11:55
Since multiple users are saying that this issue got fixed, then this issue will be closed. If someone re-encounters this issue or has any other feedback, please open a new issue. Thanks for your contribution to Paperwork.

**Closed by Liongold** 2017-02-07 11:55 UTC
Labels: pending feedback

**Comment by davidtessier** [comment] 2017-06-02 13:27
I have reviewed this thread and am in the same boat. 
I enforce HTTPS on my server if that matters. 
I have mod enable rewrite on.
I have done a chown www-data * -R on the paperwork folder.

My issues are the same as above:

I get to step 4 and am presented with "Configuration has not been set correctly. Please try again."
When I look at the Chrome console it says setup/setConfig not found (404).
The database.json file is created in app/storage/config but the paperwork.json isn't. I do see the default-paperwork.json file though.

I am not using nginx, but a standard LAMP setup on Ubuntu 16.04.

I've been really interested in this software for weeks and have been struggling to get past this step but can't figure out what to do. It may be a permission issue, but I'm not a monster server admin yet so I may need pointers on what else I can do besides the chown.

**Comment by codejockey1** [comment] 2017-06-06 20:55
Having the same issue and I've attempted all of the above with no luck. 
http://<%host%>/paperwork/frontend/public/setup/installDatabase returns a 404

I'm missing files in /public/setup:
/var/www/paperwork/frontend/public/setup $ ls -l
total 12
-rwxrwxrwx 1 root root 1791 Jun  6 14:45 check_database_credentials.php
-rwxrwxrwx 1 root root  589 Jun  6 14:45 convert_settings.php
-rwxrwxrwx 1 root root  200 Jun  6 14:45 update_step.php

**Comment by Liongold** [comment] 2017-06-07 13:54
Are you trying to access Paperwork from a subfolder, like domainname/paperwork? The request you're mentioning should be domainname/setup/installDatabase, the paperwork/frontend/public/ part should not be in the URL.

**Comment by codejockey1** [comment] 2017-06-07 15:12
@Liongold Correct, I'm using domainname/paperwork/

**Comment by Liongold** [comment] 2017-06-07 19:15
Paperwork is built on top of Laravel that is designed to work outside of subfolders (meaning domainname only without /paperwork/). Can you try using Paperwork in that way?

**Comment by codejockey1** [comment] 2017-06-08 02:29
With that, I was able to get everything working. Thanks for your help!

**Comment by marcbritten** [comment] 2017-10-07 23:03
Just wanted to drop a note that the main cause of the setConfig failed error is missing         try_files $uri $uri/ /index.php; from the nginx config

thought I had everything right and didn't.  Since this seems to have been logged several times with no one posting what worked I figured I would drop this here.

**Comment by Liongold** [comment] 2017-12-21 14:31
@marcbritten Can you edit the wiki to point out this tip please?
