### ISSUE TITLE
On tags input

### ISSUE THREAD

**Issue by pradeepsekart** [twostairs/paperwork#126] opened 2015-01-27 10:54 UTC
![ss](https://cloud.githubusercontent.com/assets/9690835/5917304/43e11cfa-a641-11e4-96f0-2a9f38182452.png)
After creating the tags, the tag text of the created tag is duplicated.

**Comment by devilx** [comment] 2015-01-27 11:34
Duplicate of #101.

**Closed by devilx** 2015-01-27 11:34 UTC
Labels: duplicate
