### ISSUE TITLE
Last tag duplicates itself

### ISSUE THREAD

**Issue by y5j7k2** [twostairs/paperwork#99] opened 2015-01-26 00:35 UTC
When I write tags separated by commas and hit enter, the last tag is "tagged" (blue decoration) but gets repeated in the end in plain text.

**Comment by OmgImAlexis** [comment] 2015-01-26 04:42
#101

**Comment by devilx** [comment] 2015-01-26 09:44
Actually #101 is a duplicate of #99. :-) But since #101 has a screenshot attached, let's pick that one. @y5j7k2 thanks for reporting! You might add yourself cc to #99 now.

**Closed by devilx** 2015-01-26 09:44 UTC
Labels: duplicate
