### ISSUE TITLE
Tidy up all angular code according code style

### ISSUE THREAD

**Issue by Baldrs** [twostairs/paperwork#112] opened 2015-01-26 15:36 UTC
Having all scripts lying around as junk without any particular structure is a bad practice, especially in angular applications. And all javascript should be organized as well.

https://github.com/johnpapa/angularjs-styleguide
https://github.com/johnpapa/angularjs-styleguide#application-structure

**Comment by devilx** [comment] 2015-01-26 17:17
Basically there is *some* structure, even though it might not be perfect. I'm thankful for anyone better with AngularJS than I am taking a look at it and refactoring everything that's implemented improperly. :+1:

**Comment by devilx** [comment] 2015-01-26 17:18
PS: Duplicate of #17. Sorry. :-)

**Closed by devilx** 2015-01-26 17:18 UTC
Labels: duplicate

**Comment by Baldrs** [comment] 2015-01-27 05:42
Am I welcome to submit a pull requests on some issues?

**Comment by devilx** [comment] 2015-01-27 08:50
@Baldrs you are welcome! :-)
