### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by kuc** [twostairs/paperwork#697] opened 2016-10-10 09:04 UTC
There seems to be a frequent problem with basic functionality not working in this project. Firstly I thought that at least we have unit tests in place... but after investigation, they are nothing more than decoration 😞 

I could try to write some functional tests (if I will find a time...) using e.g. [PhantomJS](http://phantomjs.org/) and integrate them with Travis build. If repo maintainers have any interest in this, of course.

**Comment by Liongold** [comment] 2016-10-10 19:33
Of course you can if you want to. Thanks for the offer and feedback. Please continue your work in #4. This seems to be a duplicate of it. I'll close it then. If you don't agree, feel free to reopen.

**Closed by Liongold** 2016-10-10 19:33 UTC

**Comment by kuc** [comment] 2016-10-10 19:35
OK, thank you! 😄
