### ISSUE TITLE
Flash of "Nothing here"

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#620] opened 2016-05-15 08:13 UTC
When entering Paperwork home page, there is a flash of "Nothing here..." before the normal UI appears.

**Comment by Liongold** [comment] 2016-05-16 14:54
A pull request has been merged with a fix for this. Please check if the issue is fixed. If yes, please reopen this issue. Thanks for your feedback.

**Closed by Liongold** 2016-05-16 14:54 UTC
