### ISSUE TITLE
Tags list update

### ISSUE THREAD

**Issue by wongalvis** [twostairs/paperwork#328] opened 2015-04-02 05:38 UTC
When a new note is created with new tags, the tab has to be refreshed in order for the tag to appear the in the sidebar list.
If I added a new note, saved, clicked "Library", the tag is not found in the sidebar. 
It would be better if the tab could be automatically refreshed, or the tag could appear without any refresh.

**Comment by clemlaf** [comment] 2015-06-29 18:03
I tried to reproduce this issue but when i click on "library", the whole page is refreshed, and then the new tag appears in the tag tree.

**Comment by Liongold** [comment] 2015-08-10 15:25
This is still happening using the latest develop branch.

**Comment by Liongold** [comment] 2016-05-09 17:15
This seems to be fixed. I haven't been able to reproduce it using Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37. Thus, I'll close this issue. If you re-encounter this issue or any other, please open a new issue. Thanks for your feedback.

**Closed by Liongold** 2016-05-09 17:15 UTC
Labels: enhancement, help wanted
