### ISSUE TITLE
Can't create a new note.

### ISSUE THREAD

**Issue by johb** [twostairs/paperwork#119] opened 2015-01-26 20:58 UTC
I can't create a new notebook if i choose "German" as a language.
I get the following error in chrome dev tools when clicking on "Create note":
POST http://demo.paperwork.rocks/api/v1/notebooks/1567/notes 500 (Internal Server Error) angular.min.js:8522

Steps to reproduce:
1. Sign up an account in demo with User Interface "German".
2. Create a new notebook.
3. Select this notebook and try to create a new note ("Neue Notiz").

**Comment by devilx** [comment] 2015-01-26 21:59
Duplicate of #100. Please feel free to subscribe there!

**Closed by devilx** 2015-01-26 21:59 UTC
Labels: duplicate
