### ISSUE TITLE
Make a 'webclipper' like Evernote for Chrome

### ISSUE THREAD

**Issue by plainspace** [twostairs/paperwork#91] opened 2015-01-25 16:48 UTC
https://evernote.com/webclipper/

https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc?hl=en

**Comment by Liongold** [comment] 2015-01-25 17:07
Duplicate of #62

**Closed by Liongold** 2015-01-25 17:07 UTC
